/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.hedymacferran.tests.FlashVarTest;
	import com.hedymacferran.tests.HomeLinkVOTest;
	
	import flash.display.Sprite;
	import com.hedymacferran.tests.HedyModelTest;
	import com.hedymacferran.tests.DataServiceTest;
	import com.hedymacferran.tests.JSONServiceTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var com_hedymacferran_tests_JSONServiceTest_obj:com.hedymacferran.tests.JSONServiceTest;
		private var com_hedymacferran_tests_DataServiceTest_obj:com.hedymacferran.tests.DataServiceTest;
		
		private var com_hedymacferran_tests_HedyModelTest_obj:com.hedymacferran.tests.HedyModelTest;
		
		private var com_hedymacferran_tests_FlashVarTest_obj:com.hedymacferran.tests.FlashVarTest;
		private var com_hedymacferran_tests_HomeLinkVOTest_obj:com.hedymacferran.tests.HomeLinkVOTest;
	}
}